### ISSUE TITLE
Possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by MaxShv** [sylvinus/node-crawler#130]
Does anyone know what may cause this issue?

```
{"level":"error","message":"(node) warning: possible EventEmitter memory leak detected. 11 listeners added. Use emitter.setMaxListeners() to increase limit."}
{"level":"error","message":"Trace\n    at Request.EventEmitter.addListener (events.js:160:15)\n    at Request.start (/node_modules/crawler/node_modules/request/request.js:829:8)\n    at Request.end (/node_modules/crawler/node_modules/request/request.js:1471:28)\n    at end (/node_modules/crawler/node_modules/request/request.js:538:16)\n    at /node_modules/crawler/node_modules/request/request.js:552:9\n    at process._tickCallback (node.js:415:13)"}
```

**Comment by paulvalla** [comment]
What was your issue ?

**Comment by zycbobby** [comment]
I crawl one page and got this warning:

> (node) warning: possible EventEmitter memory leak detected. 11 end listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at Request.addListener (events.js:179:15)
    at Request.onResponse (/home/zuo/Code/easy_download/node_modules/crawler/node_modules/request/request.js:1108:12)
    at ClientRequest.g (events.js:199:16)
    at ClientRequest.emit (events.js:107:17)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:419:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_client.js:310:20)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
    at Socket.Readable.push (_stream_readable.js:126:10)

I have tried in node v0.10.38, node v0.12.0, node v0.12.1 on ubuntu14.04.

Is there any support for this problem?

**Comment by zycbobby** [comment]
OK, if some one reach this problem again.. you can try [17118d44aa0792d36035fb6c4ba3485608c313b2](https://github.com/zycbobby/node-crawler/commit/17118d44aa0792d36035fb6c4ba3485608c313b2)
