### ISSUE TITLE
TypeError when running webcrawler

### ISSUE THREAD

**Issue by DanielDeychakiwsky** [sylvinus/node-crawler#136]
Here is the error: 

Any idea why I'm getting this. I have callback defined.

TypeError: undefined is not a function
    at Object.Crawler.callback (/Users/integral/Documents/github/DevDoodles/DevDoodles/webcrawler/js/main.js:14:9)
    at Crawler._onContent (/Users/integral/Documents/github/DevDoodles/DevDoodles/webcrawler/node_modules/crawler/lib/crawler.js:462:17)
    at Request._callback (/Users/integral/Documents/github/DevDoodles/DevDoodles/webcrawler/node_modules/crawler/lib/crawler.js:352:18)
    at Request.self.callback (/Users/integral/Documents/github/DevDoodles/DevDoodles/webcrawler/node_modules/crawler/node_modules/request/request.js:236:22)
    at Request.emit (events.js:98:17)
    at Request.<anonymous> (/Users/integral/Documents/github/DevDoodles/DevDoodles/webcrawler/node_modules/crawler/node_modules/request/request.js:1142:14)
    at Request.emit (events.js:117:20)
    at IncomingMessage.<anonymous> (/Users/integral/Documents/github/DevDoodles/DevDoodles/webcrawler/node_modules/crawler/node_modules/request/request.js:1096:12)
    at IncomingMessage.emit (events.js:117:20)
    at _stream_readable.js:944:16

Here is my simple implementation:

var Crawler = require("crawler");

var c = new Crawler({
    maxConnections : 10,
    // This will be called for each crawled page
    callback : function (error, result, $) {

        if (error){
            // Handle error
        } 

        // $ is Cheerio by default
        //a lean implementation of core jQuery designed specifically for the server
        $('a').each(function(index, a) {
            var toQueueUrl = $(a).attr('href');
            //show urls in console
            console.log(toQueueUrl);
            c.queue(toQueueUrl);
        });
    },

    // This will be called when crawler has empty queue
    onDrain : function(){
        console.log('nothing more to crawl');
    }
});

// Queue just one URL, with default callback, start at cnn
c.queue('http://cnn.com');

**Comment by DanielDeychakiwsky** [comment]
Ok, this may be due to the fact that the crawler reaches a page that has no <a> tags.

**Comment by DanielDeychakiwsky** [comment]
Actually it seems that jQuery might be failing to be injected or something among those lines, I still get the error - even after implementing a check for pages with no 'a' tags

**Comment by simongfxu** [comment]
you lost `jQuery: true`?
